### ISSUE TITLE
Dependancies

### ISSUE THREAD

**Issue by robotastic** [leswright1977/RPi4-Google-Coral#2]
I need to install a couple dependencies. This seemed to solve it for me:

````
pip3 install opencv-python; sudo apt-get install -y libhdf5-dev libhdf5-serial-dev libatlas-base-dev libjasper-dev  libqtgui4  libqt4-test
````

**Comment by leswright1977** [comment]
Glad you fixed it. I could re roll the script to pull in all the deps first on future builds.
